---
title: "practice writing code of R for assingment2"
author: "Ryo uchimido"
date: "10/24/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#setwd("~/data/HST.953") # Students will need to set their own path or see below
 if(!("Hmisc" %in% installed.packages()[,1])) {
 install.packages("Hmisc")
 }

library(Hmisc)

```

```{r}
dat <- read.csv("/Users/uchimidouryou/Documents/aline-dataset.csv")
dim(dat)

dat$age.cat <- cut2(dat$age,g=4)  # Added so the file will compile.  You will need to update this variable later on.
dat$service_unit2 <- dat$service_unit=="MICU"  # Added so the file will compile.  You will need to update this variable later on.

```
```{r}
plot(dat$bun_first,dat$creatinine_first)
```
```{r}
with(dat,plot(bun_first,creatinine_first))

####same???
```

```{r}
plot(log(dat$bun_first),-1/dat$creatinine_first^(1/3))

```

```{r}
bun.creat.lm <- lm(I(-1/dat$creatinine_first^(1/3)) ~ I(log(bun_first)), data=dat)
summary(bun.creat.lm)
```

```{r}
confint(bun.creat.lm)
```

```{r}
library(sjPlot)
```
```{r}
install.packages("TMB")
```
```{r}
library(sjPlot)
```

###????? do I nead to slove this warning?

```{r}
sjp.lm(bun.creat.lm,type = "coef")
```
```{r}
plot(log(dat$bun_first), -1/dat$creatinine_first^(1/3),pch=19)
abline(bun.creat.lm,col='red')
```
```{r}
dat$renal_flg <- as.factor(dat$renal_flg)

##why we have to make renal_flag a factor?????
```
```{r}
#plot(log(dat$bun_first), -1/dat$creatinine_first^(1/3),pch=19)
plot(log(dat$bun_first),-1/dat$creatinine_first^(1/3),pch=19)
```
```{r}
plot(log(dat$bun_first),-1/dat$creatinine_first^(1/3),pch=19,col=dat$renal_flg)
```



```{r}
with(dat,plot(log(bun_first),-1/creatinine_first^(1/3),col=renal_flg,pch=19))

## same plot

# in with don't need to put "dat$" before variable, it is OK if you put dat just after with
```

```{r}
bun.creat.renal.con.lm <-lm(I(-1/dat$creatinine_first^(1/3)) ~ I(log(bun_first)) + renal_flg,data = dat)
summary(bun.creat.renal.con.lm)
```

```{r}
bun.creat.renal.int.lm <- lm(I(-1/dat$creatinine_first^(1/3)) ~ I(log(bun_first)) * renal_flg,data = dat)

## what is the diffrence bet + and * ????
summary(bun.creat.renal.int.lm)
```

```{r}
anova(bun.creat.renal.con.lm,bun.creat.renal.int.lm)

#what is the null hypothesis of F-test here?
```

```{r}
anova(bun.creat.lm,bun.creat.renal.con.lm)
```



```{r}
plot(log(dat$bun_first),-1/dat$creatinine_first^(1/3),pch=19,col=dat$renal_flg)
abline(a=coef(bun.creat.renal.lm)[1],b=coef(bun.creat.renal.lm)[2],col="blue",lwd=2)
abline(a=sum(coef(bun.creat.renal.lm)[c(1,3)]),b=coef(bun.creat.renal.lm)[2],col="red",lwd=2)
```

```{r}
aline.glm<-glm(day_28_flg ~ aline_flg,data = dat, family="binomial")
summary(aline.glm)
```

```{r}
names(aline.glm)
aline.glm[[1]]
aline.glm[[1]][1]
coef(aline.glm)[1]
exp(coef(aline.glm)[1])
```

```{r}
confint(aline.glm)
```

```{r}
exp(confint(aline.glm))
```
```{r}
sjp.glm(aline.glm)
```
```{r}
tab22 <- table(dat$aline_flg,dat$day_28_flg,dnn=c("Aline","28 day death"))
ptab22 <- prop.table(tab22,1)
Oddstab22 <-ptab22[,2]/ptab22[,1]
Oddstab22[2]/Oddstab22[1]
```

```{r}
sofa.glm<-glm(day_28_flg ~ sofa_first, data = dat, family = "binomial")
summary(sofa.glm)
```
```{r}
sjp.glm(sofa.glm)
```
```{r}
library(MIMICbook); library(Hmisc)
dat$sofa_cat <-cut2(dat$sofa_first,c(0,4,7))
plot_prop_by_level(dat,"sofa_cat","day_28_flg")
```
```{r}
plot_OR_by_level(dat,"sofa_cat", "day_28_flg")
```

```{r}
aline.sofa.glm<-glm(day_28_flg ~ aline_flg + sofa_first, data=dat, family = "binomial")
summary(aline.sofa.glm)
```

```{r}
sjp.glm(aline.sofa.glm)
```

```{r}
exp(coef(aline.sofa.glm))
exp(confint(aline.sofa.glm))

```

```{r}
anova(sofa.glm,aline.sofa.glm,test = "Chisq")
```

